# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0822677fc60e9ed6c0ef741f9feba11562cd3c577295b7f89bc7a6cd024c29f1aab7c6a26d3aaab362637c08975111e839166f239abcf5c055b8a1471a0312b1

test:
  secret_key_base: e3ea83195002f9124d10e5fd897a440ffe406169950f9abe4f705654f7a3147577bfb6ee08325a64261581d21cd4c44aa2bf7cc8b17ea825e87b1b5d4143913a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
